defaults: &defaults
  access_key_id: "837990458163"
  secret_access_key: "b841bcca26d99f6dc49818a17ce0f522ab3f1e9923f0e2f99a9197a7addc182f"
  bucket: "kapp10"
development:
  <<: *defaults
test:
  <<: *defaults
staging:
  <<: *defaults
production:
  <<: *defaults
