development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: freshstart_dev
  pool: 20
  username: IBI
  password:

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: freshstart_test
  pool: 20
  username: IBI
  password:

production:
  adapter: postgresql
  encoding: utf8
  url: <%= ENV["DATABASE_URL"] %>
  database: freshstart_production
  pool: 50