development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: freshstart-dev2
  pool: 20
  username: <%=ENV["DATABASE_USER"]%>
  password:

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: freshstart_test
  pool: 20
  username: <%=ENV["DATABASE_USER"]%>
  password:

staging:
  adapter: postgresql
  encoding: utf8
  url: <%= ENV["DATABASE_URL"] %>
  database: freshstart_staging
  pool: 50

production:
  adapter: postgresql
  encoding: utf8
  url: <%= ENV["DATABASE_URL"] %>
  database: freshstart_production
  pool: 50
