# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24fb0742d69ea50c5762a8884b480effe84b41766ad06225e8a01d587b140394cd4808ee3f42cfcd9062ff935f5aea7c306b4cba28493fcf2e08f043081e1a77
  #aws_access_key_id: AKIAIT5MGBQ56BK3QPSQ
  #aws_secret_access_key: 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
  #aws_region: eu-west-1
  #aws_buket: sportpics-photos

test:
  secret_key_base: c786aba58f64337fe57f365c242c29d9ca69d75280d03bf87e07b9bc854f4131eaf972998e22f929dc1baddc4a0bbc0bd2001671116d5bd38462500ceb5db3da

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
